In [2]:
import numpy as np
import pandas as pd

In [4]:
caption_tn_test = pd.read_csv("/Data2/Arun-UAV/NLP/vision_halu/haloc/train_dataset/caption/tn_test.csv")
caption_tp_test = pd.read_csv("/Data2/Arun-UAV/NLP/vision_halu/haloc/train_dataset/caption/tp_test.csv")

In [10]:
caption_tn_test.shape

(3273, 11)

In [44]:
caption_tp_test

,Unnamed: 0,image_id,prompt,hallucinated_text,source_text,source_metadata,qa_metadata,qa_ids,annotations,id,split
0,64796,2391368,<image>Can you describe the main features of t...,"In this image, there are some boxes that conta...","In this image, there are some boxes contains f...","{'source': 'localized_narratives', 'id': 'sp_2...",[],['001006084'],"{'object': [], 'attribute': [{'attribute': {'n...",caption_4,test
1,64797,2375207,<image>Write a detailed description of the giv...,A man is wearing a white uniform. He is wearin...,A man is wearing a white uniform. He is wearin...,"{'source': 'stanford', 'id': 'sp_30231'}",[],['001021520'],"{'object': [], 'attribute': [{'attribute': {'n...",caption_11,test
2,64798,2351441,<image>Analyze the image in a comprehensive an...,there are three people on skis. they are treck...,there are three people on skis. they are treck...,"{'source': 'stanford', 'id': 'sp_26758'}",[],"['00116341', '00116312']","{'object': [{'obj': {'name': 'motorcycle', 'ch...",caption_38,test
3,64799,2382256,<image>Explain the visual content of the image...,This is the dog sitting on the floor. Here is ...,This is the dog sitting on the floor. Here is ...,"{'source': 'localized_narratives', 'id': 'sp_2...",[],['00141230'],"{'object': [], 'attribute': [{'attribute': {'n...",caption_42,test
4,64800,2386140,<image>What's happening in the scene?,A white kite with a green streamer is flying i...,A white kite with a green streamer is flying i...,"{'source': 'stanford', 'id': 'sp_32416'}",[],['00149629'],"{'object': [], 'attribute': [{'attribute': {'n...",caption_47,test
...,...,...,...,...,...,...,...,...,...,...,...
3268,68064,2325153,<image>What is this photo about?,In this image on the left side there is one bi...,In this image on the left side there is one bi...,"{'source': 'localized_narratives', 'id': 'sp_2...",[],"['c_19143552', 'c_19143441']","{'object': [], 'attribute': [{'attribute': {'n...",caption_35586,test
3269,68065,2349123,<image>Explain the visual content of the image...,This picture might be taken outside of the cit...,This picture might be taken outside of the cit...,"{'source': 'localized_narratives', 'id': 'sp_2...",[],['c_19162799'],"{'object': [], 'attribute': [{'attribute': {'n...",caption_35587,test
3270,68066,2412251,<image>What are the key elements in this picture?,A white cutting board is sitting on a counter....,A white cutting board is sitting on a counter....,"{'source': 'stanford', 'id': 'sp_28312'}",[],['c_1938654'],"{'object': [], 'attribute': [{'attribute': {'n...",caption_35603,test
3271,68067,2407341,<image>Can you elaborate on the elements of th...,Here we can see few brown boats on the water. ...,Here we can see few boats on the water. In the...,"{'source': 'localized_narratives', 'id': 'sp_1...",[],['c_19841123'],"{'object': [], 'attribute': [{'attribute': {'n...",caption_35655,test
3272,68068,2382352,<image>Describe the following image.,In this image there is a person wearing a whit...,In this image there is a person wearing a whit...,"{'source': 'localized_narratives', 'id': 'sp_1...",[],['c_19925471'],"{'object': [], 'attribute': [{'attribute': {'n...",caption_35662,test

In [45]:
target_test = caption_tp_test

In [53]:
from tqdm import tqdm
all_target_words = []
for res in tqdm(target_test["annotations"]):
    res = eval(res)
    obj_df = pd.DataFrame(res["object"])
    attr_df = pd.DataFrame(res["attribute"])
    rel_df = pd.DataFrame(res["relationship"])
    scene_df = pd.DataFrame(res["scene"])


    target_words = []
    if not obj_df.empty:
        for index, row in obj_df.iterrows():
            target_words.append({"word" : row["obj"]["name"], "type": "object", "label": "halu"})

    if not attr_df.empty:
        for index, row in attr_df.iterrows():
            target_words.append({"word" : row["attribute"]["name"], "type": "attribute", "label": "halu"})

    if not rel_df.empty:
    
        for index, row in rel_df.iterrows():
            target_words.append({"word" : row["predicate"]["name"], "type": "relationship", "label": "halu"})

    if not scene_df.empty:
        for index, row in scene_df.iterrows():
            target_words.append({"word" : row["scene"]["name"], "type": "scene", "label": "halu"})
    
    all_target_words.append(target_words)

100%|██████████| 3273/3273 [00:02<00:00, 1214.02it/s]

In [54]:
target_test["extracted_target_words"] = all_target_words

In [ ]:
target_test.to_csv("")

,Unnamed: 0,image_id,prompt,hallucinated_text,source_text,source_metadata,qa_metadata,qa_ids,annotations,id,split,extracted_target_words
0,64796,2391368,<image>Can you describe the main features of t...,"In this image, there are some boxes that conta...","In this image, there are some boxes contains f...","{'source': 'localized_narratives', 'id': 'sp_2...",[],['001006084'],"{'object': [], 'attribute': [{'attribute': {'n...",caption_4,test,"[{'word': 'wicker', 'type': 'attribute', 'labe..."
1,64797,2375207,<image>Write a detailed description of the giv...,A man is wearing a white uniform. He is wearin...,A man is wearing a white uniform. He is wearin...,"{'source': 'stanford', 'id': 'sp_30231'}",[],['001021520'],"{'object': [], 'attribute': [{'attribute': {'n...",caption_11,test,"[{'word': 'plastic', 'type': 'attribute', 'lab..."