In [4]:
import nltk
nltk.download('wordnet', download_dir='/Data2/Arun-UAV/NLP/vision_halu/')

[nltk_data] Downloading package wordnet to /Data2/Arun-
[nltk_data]     UAV/NLP/vision_halu/...
[nltk_data]   Package wordnet is already up-to-date!

True

In [6]:
# import nltk
# import os

# # ✅ Set your custom download path
# NLTK_DIR = "/Data2/Arun-UAV/NLP/vision_halu/nltk_data"
# os.makedirs(NLTK_DIR, exist_ok=True)

# # ✅ Tell NLTK to use this path
# nltk.data.path.append(NLTK_DIR)

# # ✅ List of recommended packages
# packages = [
#     "punkt",
#     "punkt_tab",
#     "stopwords",
#     "wordnet",
#     "omw-1.4",
#     "averaged_perceptron_tagger",
#     "averaged_perceptron_tagger_eng",
#     "maxent_ne_chunker",
#     "words",
#     "treebank",
#     "brown",
#     "movie_reviews",
#     "subjectivity",
#     "reuters",
#     "names",
#     "conll2000",
#     "dependency_treebank",
#     "tagsets"
# ]

# # ✅ Download all
# for pkg in packages:
#     print(f"Downloading: {pkg}")
#     nltk.download(pkg, download_dir=NLTK_DIR)

# print("\n✅ All NLTK resources downloaded successfully to:", NLTK_DIR)

In [17]:
import pandas as pd
data = pd.read_json("/Data2/Arun-UAV/NLP/vision_halu/testing_res/chair_llava_base_des_02_11_2025.jsonl", lines=True)

In [19]:
data.head(2)

,question,answer,question_id,image_id,image_path,data_type,generated_captions
0,Please describe this image in detail.,"{'total_image_description': 'A close-up, high-...",0,226988,/Data2/Arun-UAV/NLP/vision_halu/benchmarks/coc...,no_datatype,The image features a woman sitting at a dining...
1,Please describe this image in detail.,{'total_image_description': 'The image capture...,1,337443,/Data2/Arun-UAV/NLP/vision_halu/benchmarks/coc...,no_datatype,The image features a busy street with several ...

In [20]:
data = pd.read_json("/Data2/Arun-UAV/NLP/vision_halu/benchmarks/amber/llava_res/amber_llava_base_des_all_res_02_11_2025.json", lines=True, orient="records")

In [21]:
data.head(2)

,question,answer,question_id,image_id,image_path,data_type,generated_captions
0,Describe this image.,no-answer,1,AMBER_1.jpg,/Data2/Arun-UAV/NLP/vision_halu/benchmarks/amb...,no_datatype,The image depicts a group of four people walki...
1,Describe this image.,no-answer,2,AMBER_2.jpg,/Data2/Arun-UAV/NLP/vision_halu/benchmarks/amb...,no_datatype,The image features a man wearing a life jacket...